check_reqs: add check for build requires

diff --git a/share/eterbuild/korinf/check_reqs b/share/eterbuild/korinf/check_reqs
--- a/share/eterbuild/korinf/check_reqs
+++ b/share/eterbuild/korinf/check_reqs
@@ -46,21 +46,45 @@ expand_mask_in_dir()
 	done
 }
 
+# args: dist file reqs
+print_check_reqs_item()
+{
+	local dist=$1
+	local fname=$(basename $2)
+	shift 2
+	local reqs=$@
+
+	if [ "$CHECKREQUIRES" = "-R" ] ; then
+		printf "* %s: %s" "$fname" "$(echo $reqs)"
+		[ -z "$reqs" ] && echo "EMPTY" && continue
+		echo
+		try_install_by_list $dist "$reqs" && echo "  OK" || echo "FAIL"
+	else
+		printf "  * %60s: " "$fname"
+		[ -z "$reqs" ] && echo "Empty list" && continue
+		try_install_by_list $dist "$reqs" >/dev/null 2>&1 && echo "  OK" || echo "FAIL"
+	fi
+}
+
+
 # check package existing by REBUILDLIST
 # used: TARGETPATH REBUILDLIST
 check_package_requires()
 {
 	local BUILDNAME=$1
+	local SRCPKG
+	local reqs
 
 	if [ ! -d "$TARGETPATH" ] ; then
 		echo "Path TARGETPATH:'$TARGETPATH' is missed"
 		return 1
 	fi
 
-	test -L "$TARGETPATH/$i" && continue
+	test -L "$TARGETPATH/$dist" && continue
 
-	#SRCPKG=$(get_src_package "$SOURCEPATH" $BUILDNAME)
-	#[ -n "$QUIET" ] || echo "Source package: $SRCPKG"
+	echo "Note: we do not use info from built packages, only check if file is exists"
+	SRCPKG=$(get_src_package "$SOURCEPATH" $BUILDNAME)
+	[ -n "$QUIET" ] || echo "Source package: $SRCPKG"
 
 	for dist in $(get_distro_list $REBUILDLIST) ; do
 		# fills $BUILDARCH, $DISTRNAME, $DISTRVERSION
@@ -72,20 +96,17 @@ check_package_requires()
 		prepare_filelist
 		[ "$CHECKREQUIRES" = "-R" ] && echo "====================="
 		printf "%-20s\n" "$BUILDARCH/$DISTRNAME/$DISTRVERSION"
+
+		# first print about source package
+		reqs=$(get_rpmpkg_requires -p $SRCPKG)
+		reqs=$(convert_pkgreqs_to_target $reqs)
+		print_check_reqs_item $dist $SRCPKG $reqs
+
 		for j in $(expand_mask_in_dir $TARGETPATH/$dist $EXPMAINFILES) $(expand_mask_in_dir $TARGETPATH/$dist/extra $EXPEXTRAFILES) ; do
 			[ -r "$j" ] || continue
 			pkgname=$(get_pkgname_from_filename $j)
 			reqs=$(get_target_deplist $pkgname)
-			if [ "$CHECKREQUIRES" = "-R" ] ; then
-				printf "* %s: %s" "$(basename $j)" "$(echo $reqs)"
-				[ -z "$reqs" ] && echo "EMPTY" && continue
-				echo
-				try_install_by_list $dist "$reqs" && echo "  OK" || echo "FAIL"
-			else
-				printf "  * %60s: " "$(basename $j)"
-				[ -z "$reqs" ] && echo "Empty list" && continue
-				try_install_by_list $dist "$reqs" >/dev/null 2>&1 && echo "  OK" || echo "FAIL"
-			fi
+			print_check_reqs_item $dist $j $reqs
 		done
 	done
 }
