move buildlist and target distro related func from common to korinf

diff --git a/share/eterbuild/korinf/common b/share/eterbuild/korinf/common
--- a/share/eterbuild/korinf/common
+++ b/share/eterbuild/korinf/common
@@ -177,4 +177,44 @@ get_distro_list()
 	done
 }
 
+# get distro list from TARGETPATH or lists/all
+get_target_list()
+{
+	local TLIST
+	TLIST=$TARGETPATH/distro.list
+	[ -r "$TLIST" ] || TLIST=$KORINFETC/lists/all
+	[ -r "$TLIST" ] || fatal "get_target_list failed to get full list of targets"
+	echo $TLIST
+}
+
+check_target_dist()
+{
+	local DIST="$1"
+	get_distro_list $(get_target_list) | grep -q "$DIST"
+}
+
+# Set REBUILDLIST according TARGETPATH, existing REBUILDLIST and some heruistic
+set_rebuildlist()
+{
+	local RESULT
+	if [ -n "$REBUILDLIST" ] ; then
+		if [ -r "$KORINFETC/lists/$REBUILDLIST" ] ; then
+			REBUILDLIST=$KORINFETC/lists/$REBUILDLIST
+			RESULT="Build for distros from $REBUILDLIST"
+		else
+			check_target_dist $REBUILDLIST || fatal "Run with unknown target '$REBUILDLIST'"
+			RESULT="Build for $REBUILDLIST"
+		fi
+	else
+		REBUILDLIST=$(get_target_list)
+		# Hack?
+		if [ -r "$TARGETPATH/distro.list" ] ; then
+			RESULT="Build according to distro.list from $TARGETPATH"
+		else
+			RESULT="Build for distros from $REBUILDLIST"
+		fi
+	fi
+	[ -n "$QUIET" ] || echo $RESULT
+}
+
 kormod config log
