some build fixes

diff --git a/share/eterbuild/korinf/config b/share/eterbuild/korinf/config
--- a/share/eterbuild/korinf/config
+++ b/share/eterbuild/korinf/config
@@ -29,5 +29,37 @@ mkdir -p $CHROOTDIR
 test -f $KORINFETC/korinf && . $KORINFETC/korinf
 test -f ~/.config/korinf  && . ~/.config/korinf
 
+init_home()
+{
+	if [ ! -d $BUILDERHOME/ ] ; then
+		return
+	fi
+
+	# FIXME: ebconfig is obsolete
+	[ -r $BUILDERHOME/.ebconfig ] || echo "RPMBUILD=rpmbuild" > $BUILDERHOME/.ebconfig
+
+	if [ -r $BUILDERHOME/.rpmmacros ] ; then
+		return
+	fi
+
+cat <<EOF >$BUILDERHOME/.rpmmacros || fatal "Can't copy macros"
+# Etersoft's default macros
+%_topdir        /home/$INTUSER/RPM
+%_tmppath       /home/$INTUSER/tmp
+%_sourcedir %_topdir/SOURCES
+%vendor Etersoft
+%distribution WINE@Etersoft
+#%_target_cpu i586
+%buildhost builder.etersoft.ru
+# do wrong (crossed with --buildroot?
+#%BuildRoot: %_tmppath/%{name}-%{version}
+#%buildroot: %_tmppath/%{name}-%{version}
+%packager Etersoft Builder <support@etersoft.ru>
+
+# see http://wiki.sisyphus.ru/devel/RpmSetup
+%_build_name_fmt %{NAME}-%{VERSION}-%{RELEASE}.%{ARCH}.rpm
+EOF
+}
+
 fi
 # end if CHROOTDIR
