set direct version

diff --git a/share/eterbuild/korinf/korinf b/share/eterbuild/korinf/korinf
--- a/share/eterbuild/korinf/korinf
+++ b/share/eterbuild/korinf/korinf
@@ -80,11 +80,20 @@ build_srcrpm()
 }
 
 
-# args: 1) path to project dir (where versions) 2) package name
+# args: 1) path to project dir (where versions) 2) package name [ 3) other project version ]
 build_project()
 {
-	TARGETPATH=$(realpath $1/last)
+	local SP
+	if [ -z "$3" ] ; then
+		SP=$1/last
+	else
+		SP=$1/$3
+	fi
+
+	TARGETPATH=$(realpath $SP)
 	SOURCEPATH=$TARGETPATH/sources
+
+	[ -n "$TARGETPATH" ] || fatal "Cannot find $SP, check it"
 
 	if [ -n "$REBUILDLIST" ] ; then
 		echo "Build for $REBUILDLIST"
