semirewrote log subsystem

diff --git a/share/eterbuild/korinf/log b/share/eterbuild/korinf/log
--- a/share/eterbuild/korinf/log
+++ b/share/eterbuild/korinf/log
@@ -7,6 +7,7 @@
 export COLUMNS=80
 kormod outformat
 
+
 success()
 {
 	MOVE_TO_COL
@@ -16,6 +17,7 @@ success()
 	SETCOLOR_NORMAL
 	echo -n ' ]'
 }
+
 
 failure()
 {
@@ -27,13 +29,40 @@ failure()
 	echo -n ']'
 }
 
+
+set_log_dir()
+{
+if [ -n "$WORKDIR" ] && [ -z "$ALOGDIR" ] ; then
+	ALOGDIR=$WORKDIR/log
+	# Hack for run from package
+	if [ ! -w "$ALOGDIR" ] ; then
+		ALOGDIR=$TMPDIR/korinf-log
+	fi
+	# Make log dir with date for builder user only
+	[ "$USER" = "builder" ] && ALOGDIR=$ALOGDIR/`date "+%Y%m%d"`
+
+	if [ -n "$1" ] ; then
+		ALOGDIR="$ALOGDIR-$1"
+	fi
+
+	# FIXME
+	[ "$WORKDIR" = `pwd` ] || mkdir -p $ALOGDIR
+	#mkdir -p $CHROOTDIR
+
+fi
+}
+
+
 init_log()
 {
+	set_log_dir
+	# FIXME: used in ELOGFILE creating
 	LLOGDIR=$ALOGDIR/${dist}
 	mkdir -p $LLOGDIR || fatal "Can't create $LLOGDIR"
 	LOGFILE=$LLOGDIR/$BUILDNAME.log
-	>$LOGFILE || fatal "Can't create log"
+	>$LOGFILE || fatal "Can't create log $LOGFILE"
 }
+
 
 copying_log()
 {
@@ -49,6 +78,7 @@ copying_log()
 	bzip $DESTLOGFILE
 }
 
+
 print_spaces_instead_string()
 {
 	local LEN STR SPACES
@@ -57,6 +87,25 @@ print_spaces_instead_string()
 	SPACES="                                                  "
 	echo "$SPACES" | cut -c 1-$LEN
 }
+
+
+write_report()
+{
+	set_log_dir
+	# FIXME: create here
+	if [ -d "$ALOGDIR" ] ; then
+		cat >> $ALOGDIR/autobuild.report.log
+	fi
+}
+
+
+write_log()
+{
+	if [ -w "$LOGFILE" ] ; then
+		cat >>$LOGFILE
+	fi
+}
+
 
 PREVSYSTEMLOGIT=
 logit()
@@ -74,7 +123,7 @@ logit()
 	[ -z "$NIGHTBUILD" ] && echo -n "$STRMSG"
 	shift
 	TIMESTAMP=`date "+%s"`
-	$* >>$LOGFILE 2>&1
+	$* 2>&1 | write_log
 	RET=$?
 	let TIMESTAMP=`date "+%s"`-$TIMESTAMP
 	[ -z "$NIGHTBUILD" ] && STRMSG=""
@@ -86,4 +135,3 @@ logit()
 	echo
 	return $RET
 }
-
