robot/funcs: use DESTDIR instead TARGETPATH

diff --git a/robot/funcs/build b/robot/funcs/build
--- a/robot/funcs/build
+++ b/robot/funcs/build
@@ -27,28 +27,28 @@
 # is not recommended include directly due message function intersection
 #kormod korinf
 
-kormod check_integrity
+kormod check_integrity status
 
 
 # Specially WINE@Etersoft case (use external DIST and PROJECTVERSION)
 check_and_refresh_package_wine()
 {
 	# Etersoft/WINE@Etersoft/last/WINE/SUSE/12
-	local TARGETPATH="$1"
+	DESTDIR="$1"
 	# get_rpm_sources will fails if target is not exists
-	mkdir -p "$TARGETPATH"
+	mkdir -p "$DESTDIR"
 	# Etersoft/WINE@Etersoft/last/sources
-	local SOURCEPATH="$(get_rpm_sources "$TARGETPATH")"
+	local SOURCEPATH="$(get_rpm_sources "$DESTDIR")"
 	# haspd
 	local BUILDNAME=$2
 
-	test -d "$SOURCEPATH" || fatal "WINE: Source path '$SOURCEPATH' doesn't exist (possibly run with incorrect target path $TARGETPATH)"
-	test -d "$TARGETPATH" || fatal "WINE: Target path '$TARGETPATH' doesn't exist"
+	test -d "$SOURCEPATH" || fatal "WINE: Source path '$SOURCEPATH' doesn't exist (possibly run with incorrect target path $DESTDIR)"
+	test -d "$DESTDIR" || fatal "WINE: Target path '$DESTDIR' doesn't exist"
 
 	# FIXMEP get_..._package always returns true
 	local SRCRPM=$(get_src_package "$SOURCEPATH" $BUILDNAME)
 	test -r "$SRCRPM" || fatal "Source package for $BUILDNAME is not found"
-	local BINPKG=$(get_bin_package "$TARGETPATH" $BUILDNAME)
+	local BINPKG=$(get_bin_package "$DESTDIR" $BUILDNAME)
 
 	# if binary is exists
 	if [ -r "$BINPKG" ] ; then
@@ -56,10 +56,11 @@ check_and_refresh_package_wine()
 		test "$BINPKG" -nt "$SRCRPM" && return 0
 	fi
 
-	[ -r "$TARGETPATH/log/$BUILDNAME.autobuild.failed" ] && fatal "Package $BUILDNAME need rebuild from $SRCRPM, but already was failed"
+	is_autobuild_failed && fatal "Package $BUILDNAME need rebuild from $SRCRPM, but already was failed"
+
 	$AROBOTDIR/../bin-wine/$BUILDNAME.sh $DIST $PROJECTVERSION && return 0
 
-	touch $TARGETPATH/log/$BUILDNAME.autobuild.failed
+	set_autobuild_failed
 	fatal "Package $BUILDNAME cannot rebuild from $SRCRPM"
 	return 1
 }
@@ -68,11 +69,11 @@ check_and_refresh_component()
 {
 	local BUILDSCRIPT="$1"
 	# Etersoft/RX@Etersoft/last/SUSE/12
-	local TARGETPATH="$2"
+	DESTDIR="$2"
 	# get_rpm_sources will fails if target is not exists
-	mkdir -p "$TARGETPATH"
+	mkdir -p "$DESTDIR"
 	# Etersoft/RX@Etersoft/last/sources
-	local SOURCEPATH="$(get_rpm_sources "$TARGETPATH")"
+	local SOURCEPATH="$(get_rpm_sources "$DESTDIR")"
 	# haspd
 	local BUILDNAME=$3
 	local PRVERSION=$4
@@ -82,13 +83,13 @@ check_and_refresh_component()
 		PRVERSION=$(basename $(dirname $SOURCEPATH) )
 	fi
 
-	test -d "$SOURCEPATH" || fatal "Source path $SOURCEPATH is not exists (run with incorrect target path $TARGETPATH)"
-	test -d "$TARGETPATH" || fatal "Target path $TARGETPATH is not exists"
+	test -d "$SOURCEPATH" || fatal "Source path $SOURCEPATH is not exists (run with incorrect target path $DESTDIR)"
+	test -d "$DESTDIR" || fatal "Target path $DESTDIR is not exists"
 
 	# FIXMEP get_..._package always returns true
 	local SRCRPM=$(get_src_package "$SOURCEPATH" $BUILDNAME)
 	test -r "$SRCRPM" || fatal "Source package for $BUILDNAME is not found"
-	local BINPKG=$(get_bin_package "$TARGETPATH" $BUILDNAME)
+	local BINPKG=$(get_bin_package "$DESTDIR" $BUILDNAME)
 
 	# if binary is exists
 	if [ -r "$BINPKG" ] ; then
@@ -100,11 +101,11 @@ check_and_refresh_component()
 		fi
 	fi
 
-	[ -r "$TARGETPATH/log/$BUILDNAME.autobuild.failed" ] && fatal "Package $BUILDNAME need rebuild from $SRCRPM, but already was failed"
+	is_autobuild_failed && fatal "Package $BUILDNAME need rebuild from $SRCRPM, but already was failed"
 
 	$AROBOTDIR/../$BUILDSCRIPT/$BUILDNAME.sh $DIST $PRVERSION && return 0
 
-	touch $TARGETPATH/log/$BUILDNAME.autobuild.failed
+	set_autobuild_failed
 	fatal "Package $BUILDNAME cannot rebuild from $SRCRPM"
 	return 1
 }
