some cleanup, add to get_src/bin_package path as first arg

diff --git a/robot/funcs/build b/robot/funcs/build
--- a/robot/funcs/build
+++ b/robot/funcs/build
@@ -26,26 +26,26 @@
 
 kormod korinf
 
+# do not used
 check_and_refresh_package()
 {
 	# Etersoft/WINE@Etersoft/last/WINE/SUSE/12
-	local TARGETPATH=$1
+	local TARGETPATH="$1"
 	# Etersoft/WINE@Etersoft/last/sources
-	local SOURCEPATH=`readlink -f $TARGETPATH/$2`
+	local SOURCEPATH="$(readlink -f "$TARGETPATH/$2")"
 	# Etersoft/WINE@Etersoft
-	local PUBPATH=`readlink -f $SOURCEPATH/../..`
+	local PUBPATH="$(readlink -f "$SOURCEPATH/../..")"
 	# WINE
-	local PUBPART=`basename $(readlink -f $TARGETPATH/../..)`
+	local PUBPART="$(basename $(readlink -f "$TARGETPATH/../.."))"
 	# haspd
 	local BUILDNAME=$3
 
+	return 1
 	# FIXMEP get_..._package always returns true
-	local SRCRPM=`get_src_package $BUILDNAME || fatal "Source package for $BUILDNAME is not found"`
-	local BINPKG=`get_bin_package $BUILDNAME || fatal "Binary package $BUILDNAME is not found"`
+	local SRCRPM=$(get_src_package $BUILDNAME || fatal "Source package for $BUILDNAME is not found")
+	local BINPKG=$(get_bin_package $BUILDNAME || fatal "Binary package $BUILDNAME is not found")
 
-	echo $BINPKG
-	echo $SRCRPM
-
+	# if binary is newer than src.rpm, return OK
 	test $BINPKG -nt $SRCRPM && return 0
 
 	#build_project $PUBPATH $BUILDNAME $PUBPART $DIST $WINENUMVERSION && return 0
@@ -54,23 +54,22 @@ check_and_refresh_package()
 	return 1
 }
 
+# Specially WINE@Etersoft case (use external DIST and WINENUMVERSION)
 check_and_refresh_package_wine()
 {
 	# Etersoft/WINE@Etersoft/last/WINE/SUSE/12
-	local TARGETPATH=$1
+	local TARGETPATH="$1"
 	# Etersoft/WINE@Etersoft/last/sources
-	local SOURCEPATH=`readlink -f $TARGETPATH/../../../sources`
+	local SOURCEPATH="$(readlink -f "$TARGETPATH/../../../sources")"
 	# haspd
 	local BUILDNAME=$2
 
 	# FIXMEP get_..._package always returns true
-	local SRCRPM=`get_src_package $BUILDNAME || fatal "Source package for $BUILDNAME is not found"`
-	local BINPKG=`get_bin_package $BUILDNAME || fatal "Binary package $BUILDNAME is not found"`
+	local SRCRPM=$(get_src_package "$SOURCEPATH" $BUILDNAME || fatal "Source package for $BUILDNAME is not found")
+	local BINPKG=$(get_bin_package "$TARGETPATH" $BUILDNAME || fatal "Binary package $BUILDNAME is not found")
 
-	echo $BINPKG
-	echo $SRCRPM
-
-	test $BINPKG -nt $SRCRPM && return 0
+	# if binary is newer than src.rpm, return OK
+	test "$BINPKG" -nt "$SRCRPM" && return 0
 
 	$AROBOTDIR/../bin-wine/$BUILDNAME.sh $DIST $WINENUMVERSION && return 0
 
