update robot remove private keys

diff --git a/robot/funcs/common b/robot/funcs/common
--- a/robot/funcs/common
+++ b/robot/funcs/common
@@ -89,7 +89,7 @@ fatal()
 	exit_now 1
 }
 
-
+# TODO: add URL checking (touch it via GET?)
 printURL()
 {
 	local FILE
@@ -101,6 +101,7 @@ printURL()
 	for i in $@ ; do
 		FILE=`basename $i`
 		# Размер файла в байтах
+		test -r "$LDIR/$FILE" || fatal "can't open $LDIR/$FILE"
 		FSIZE=`stat "--printf=%s" $LDIR/$FILE || echo 0`
 		let KSIZE=$FSIZE/1024
 		[ "$KSIZE" -lt "1" ] && KSIZE=1
@@ -110,3 +111,24 @@ printURL()
 	return 0
 }
 
+
+check_dist()
+{
+	local DIST=$1
+	REBUILDLIST=`get_distro_list $KORINFETC/lists/all | grep $DIST`
+	
+	if [ -z "$REBUILDLIST" ] ; then
+		warning "Destination $DIST is not supported for build (missed in $REBUILDLIST)"
+		do_broken
+	fi
+}
+
+# Check for package in target path
+check_package()
+{
+	local DEST=$1
+	local NAME=$2
+	local EFILE
+	EFILE=$(ls -1 $DEST/$NAME[-_][0-9]* | head -n1)
+	test -r "$EFILE" || fatal "Can't find $NAME file"
+}
diff --git a/robot/products/selta b/robot/products/selta
--- a/robot/products/selta
+++ b/robot/products/selta
@@ -51,15 +51,15 @@ ${BETA}
 EOF
 	LOCALFILES=selta.msi
 	printURL $PUBLOCAL $PUBDOWNLOAD1 $LOCALFILES >>$FILETO || fatal "Error with mirror 1 ($PUBLOCAL with '$LOCALFILES') (possible files are missed!)"
-	printURL $FTPDIR $DOWNLOADDIR/$WINENUMVERSION `( cd $FTPDIR && find -L ./ -maxdepth 1 -type f | sed -e "s|\./||g" )` >>$FILETO || fatal "Error with private part (files are missed) "
+	printURL $FTPDIR $DOWNLOADDIR/$WINENUMVERSION `find -L  $FTPDIR -maxdepth 1 -type f ` >>$FILETO || fatal "Error with private part (files are missed) "
 
 	cat >>$FILETO <<EOF
 
 Пакеты PostgreSQL для системы ${TEXTDIST} (файлы postgresql*):
 EOF
 
-	LOCALFILES=`( cd $PGLOCAL ; find -L $DIST -maxdepth 1 -type f)`
-	printURL $PGLOCAL $PGDOWNLOAD1 $LOCALFILES >>$FILETO || fatal "Error with mirror 1 ($PGLOCAL with '$LOCALFILES') (possible files are missed!)"
+	LOCALFILES=`find -L $PGLOCAL/$DIST -maxdepth 1 -type f`
+	printURL $PGLOCAL/$DIST $PGDOWNLOAD1/$DIST $LOCALFILES >>$FILETO || fatal "Error with mirror 1 ($PGLOCAL with '$LOCALFILES') (possible files are missed!)"
 
 
 	cat >>$FILETO <<EOF
@@ -78,7 +78,7 @@ http://wiki.etersoft.ru/SELTA
 Благодарим Вас за покупку!
 -- 
 Команда разработчиков
-Etersoft, 2008
+Etersoft, 2009
 EOF
 }
 
@@ -109,14 +109,8 @@ build_selta()
 		TEXTDIST="$TEXTDIST (фактически сборка выполнена для $DIST)"
 	fi
 	
-	# grep line for DIST
-	export REBUILDLIST=`grep -v "^#" lists/rebuild.list.all | grep $DIST`
-	
-	if [ -z "$REBUILDLIST" ] ; then
-		warning "Destination $DIST is not supported for build (missed in $REBUILDLIST)"
-		do_broken
-	fi
-
+	check_dist $DIST
+	REBUILDLIST=$DIST
 	echo "Work with $TASK for $REBUILDLIST"
 
 	export FTPDIR=$TARGETDIR/$WINENUMVERSION
@@ -131,46 +125,10 @@ build_selta()
 	# Вывод скрипта не записывается в лог
 	export BUILDSTRAP=
 	#
-
-# Подпись
-	unset DISPLAY
-	# Ключ в private_key.dsa
-	cd sig
-	#LICENSE_FILE=$TARGETDIRNAME.lic
-	LICENSE_FILE=selta.lic
-	test -r $LICENSE_FILE && fatal "Some license file already exists"
-#TYPE_LICENSE=Corporate
-cat <<EOF >$LICENSE_FILE
-VERSION=$WINENUMVERSION
-LICENSE_NUMBER=$ETERREGNUM
-OWNER=$OWNER
-RESPONSIBLE=$FULLNAME
-TYPE_LICENSE=$TYPE_LICENSE
-DATE_START=$DATE_START
-DATE_END=$DATE_END
-EOF
-	rm -f $LICENSE_FILE.sig
-	wine generate_sig.exe $LICENSE_FILE
-	rm -f $LICENSE_FILE
-	test -r $LICENSE_FILE.sig || fatal "Can't sign license file"
-	mv -f $LICENSE_FILE.sig $FTPDIR/$LICENSE_FILE || fatal "Can't move license file to $FTPDIR"
-	cd -
-	#export BUILDNAME=wine-etersoft-$type
-	#build_rpm $BUILDNAME || fatal "Build failed"
-
-	# Каталог уже создаётся сборкой пакета
-	#cd $FTPDIR && { md5sum *.* >MD5SUM ; cd - ; }
-	# вставить номер в readme и в каталог
-# поменять
-	#sed -e "s/XXXX-XXXX/$ETERREGNUM/g" <$WINEETER_PATH-$WINENUMVERSION/docs/README_$TYPE.html >$FTPDIR/README.html || fatal "readme copying"
-	#sed -e "s/XXXX-XXXX/$ETERREGNUM/g" <$WINEETER_PATH-$WINENUMVERSION/docs/license_$type.html >$FTPDIR/license.html || fatal "license copying"
-	#cp -f $WINEETER_PATH-$WINENUMVERSION/docs/${type}_manual.html $FTPDIR/manual.html || fatal "manual copying"
-
-	# Проверяем, действительно ли создался целевой файл
-	#[ -r "$EFILE" ] || fatal "Can't find result file $EFILE"
+	create_license $FTPDIR/selta.lic $AROBOTDIR/dsa/selta.dsa
 
 	# Для отправки писем обязательно нужна локаль!
-	export LANG=ru_RU.UTF-8
+	export LC_ALL=ru_RU.UTF-8
 	TMPMAIL=`mktemp`
 	prepareSeltaMail $TMPMAIL || fatal "Can't prepare letter"
 	cat $TMPMAIL | mutt "${FULLMAILTO}" -b "wine@etersoft.ru" -s "Сборка $PRODUCT" || fatal "Can't send"
diff --git a/robot/products/wine-compat b/robot/products/wine-compat
--- a/robot/products/wine-compat
+++ b/robot/products/wine-compat
@@ -149,8 +149,10 @@ EOF
 
 Россия:
 EOF
-	LOCALFILES=`( cd $PUBLOCAL ; find -L WINE/$DIST -maxdepth 1 -type f ; find -L fonts/$DIST -maxdepth 1 -type f )`
-	printURL $PUBLOCAL $PUBDOWNLOAD1 $LOCALFILES >>$FILETO || fatal "Error with mirror 1 ($PUBLOCAL with '$LOCALFILES' in '$DIST' dir) (possible files are missed!)"
+	LOCALFILES=`find -L cd $PUBLOCAL/WINE/$DIST -maxdepth 1 -type f`
+	printURL $PUBLOCAL/WINE/$DIST $PUBDOWNLOAD1/WINE/$DIST $LOCALFILES >>$FILETO || fatal "Error with mirror 1 ($PUBLOCAL with '$LOCALFILES' in '$DIST' dir) (possible files are missed!)"
+	LOCALFILES=`find -L $PUBLOCAL/fonts/$DIST -maxdepth 1 -type f`
+	printURL $PUBLOCAL/fonts/$DIST $PUBDOWNLOAD1/fonts/$DIST $LOCALFILES >>$FILETO || fatal "Error with mirror 1 ($PUBLOCAL with '$LOCALFILES' in '$DIST' dir) (possible files are missed!)"
 	echo
 	if [ -n "$PUBDOWNLOAD2" ] ; then
 		echo >>$FILETO
@@ -261,7 +263,7 @@ build_wine()
 	[ -r "$EFILE" ] || fatal "Can't find result file $EFILE"
 
 	# Для отправки писем обязательно нужна локаль!
-	export LANG=ru_RU.UTF-8
+	export LC_ALL=ru_RU.UTF-8
 	TMPMAIL=`mktemp`
 	prepareMail $TMPMAIL || fatal "Can't prepare letter"
 	cat $TMPMAIL | mutt "${FULLMAILTO}" -b "wine@etersoft.ru" -s "Сборка $PRODUCT" || fatal "Can't send"
diff --git a/robot/products/wine-etersoft b/robot/products/wine-etersoft
--- a/robot/products/wine-etersoft
+++ b/robot/products/wine-etersoft
@@ -36,10 +36,16 @@ prepare_wine_etersoft()
 	# PRODUCT_name - sql/networklite
 	PRODUCT_name=`echo "$TYPE" | sed -e "s| ||g" | tr A-Z a-z`
 	# FIXME: corp
-	license_type=""
+	if [ "$TYPE_LICENSE" = "Corporate" ] ; then
+		license_type="_corp"
+	else
+		license_type=""
+	fi
 
+	# Get file list
 	PRIVFILES=`find -L $PVTLOCAL/$DIST -maxdepth 1 -type f`
-	PUBLFILES=`find -L $PUBLOCAL/WINE/$DIST -maxdepth 1 -type f ; find -L $PUBLOCAL/fonts/$DIST -maxdepth 1 -type f`
+	PUB1FILES=`find -L $PUBLOCAL/WINE/$DIST -maxdepth 1 -type f`
+	PUB2FILES=`find -L $PUBLOCAL/fonts/$DIST -maxdepth 1 -type f`
 
 	# due ( below
 	export FTPDIR=$TARGETDIR/$TYPE-$WINENUMVERSION/$DIST
@@ -47,18 +53,21 @@ prepare_wine_etersoft()
 	# Можем стирать только каталог дистрибутива, а не весь
 	test -e $FTPDIR && rm -rf $FTPDIR
 	mkdir -p $FTPDIR/
-	# || fatal "Can't clean dest dir"
+
 	echo >> $ALOGDIR/autobuild.report.log
 	echo "Build $TYPE for $ETERREGNUM in $DIST" >> $ALOGDIR/autobuild.report.log
 
 	# Нужно скопировать файлы
-	for i in $PRIVFILES $PUBLFILES ; do
-		cp -fl $i $FTPDIR || cp -f $i $FTPDIR
+	for i in $PRIVFILES $PUB1FILES $PUB2FILES; do
+		cp -fl $i $FTPDIR || cp -f $i $FTPDIR || fatal "Can't copy $i"
 	done
 
 	create_license $FTPDIR/wine-etersoft.lic $AROBOTDIR/dsa/wine-etersoft.dsa
 
-	#EFILE=$(ls -1 $FTPDIR/$DIST/$BUILDNAME[-_][0-9]* | head -n1)
+	# Check package files
+	check_package $FTPDIR wine-etersoft
+	check_package $FTPDIR libwine-etersoft
+	check_package $FTPDIR wine-etersoft-${PRODUCT_name}
 
 	# вставить номер в readme и в каталог
 	DOCS=$PVTLOCAL/../docs
@@ -102,12 +111,16 @@ ${BETA}
 
 Для получения Продукта необходимо скачать файлы по приведённым ссылкам, в их числе:
  - документацию (файл manual.html)
+ - файл лицензии wine-etersoft.lic
  - пакеты Продукта (wine-etersoft, libwine-etersoft, wine-etersoft-$PRODUCT_name)
  - пакет haspd с драйверами аппаратных ключей защиты
 HASP 4/HL/SRM, Smartkey 3 Eutron и SafeNet Sentinel;
  - пакет со свободными шрифтами Liberation (fonts-tts-liberation).
 
 $CIFSTEXT
+
+Файл лицензии необходимо расположить в каталоге /etc/wine, ~/.wine или
+C:\WINDOWS\INF.
 
 Для полного соответствия шрифтов в программах
 рекомендуется скачать и установить пакет fonts-ttf-ms,
@@ -116,7 +129,7 @@ $CIFSTEXT
 
 Ссылки для скачивания файлов вашего экземпляра Продукта:
 EOF
-	printURL "$FTPDIR" "$DOWNLOADDIR/$TYPE-$WINENUMVERSION/$DIST" `( cd $FTPDIR ; find -L ./ -maxdepth 1 -type f | sed -e "s|\./||g" )` >>$FILETO || fatal "Error with files (files are missed) "
+	printURL "$FTPDIR" "$DOWNLOADDIR/$TYPE-$WINENUMVERSION/$DIST" `find -L $FTPDIR -maxdepth 1 -type f` >>$FILETO || fatal "Error with files (files are missed) "
 
 	cat >>$FILETO <<EOF
 (действительны в течение 4 суток)
@@ -169,7 +182,7 @@ build_wine_etersoft()
 		DIST=`readlink $PUBLOCAL/WINE/$DIST | sed -e "s|\.\./||g"`
 		TEXTDIST="$TEXTDIST (фактически сборка выполнена для $DIST)"
 	fi
-	
+	check_dist $DIST
 	
 	PUBDOWNLOAD1="ftp://updates.etersoft.ru/pub/Etersoft/$VERNAME"
 	PUBDOWNLOAD1HTTP="http://updates.etersoft.ru/pub/Etersoft/$VERNAME"
@@ -181,12 +194,10 @@ build_wine_etersoft()
 	prepare_wine_etersoft
 
 	# Для отправки писем обязательно нужна локаль!
-	locale
 	TMPMAIL=`mktemp`
 	prepare_wine_etersoft_mail $TMPMAIL || fatal "Can't prepare letter"
-	locale
-	export LANG=ru_RU.UTF-8
-	locale
+
+	export LC_ALL=ru_RU.UTF-8
 	cat $TMPMAIL | mutt "${FULLMAILTO}" -b "wine@etersoft.ru" -s "Сборка $PRODUCT" || fatal "Can't send"
 	rm -f $TMPMAIL
 }
