move convertion for Gentoo to build/gentoo script

diff --git a/share/eterbuild/korinf/build/rpm b/share/eterbuild/korinf/build/rpm
--- a/share/eterbuild/korinf/build/rpm
+++ b/share/eterbuild/korinf/build/rpm
@@ -145,13 +145,7 @@ convert_rpm()
 	case $TARGETPKGDISTRO in
 		"gentoo")
 			# Gentoo
-			echo "Using alien now"
-			run_alien --to-tgz *${BUILDNAME}*.rpm || { warning "alien problem with tbz2"; RES=11 ; }
-			for i in *${BUILDNAME}*.tgz ; do
-				local TARBNAME=`basename $i .tgz`
-				cat "$i" | gunzip -c | bzip -c > "$TARBNAME-$RELPKG.tar.bz2" || { warning "can't repack files" ; RES=11 ; }
-				rm -f "$i"
-			done
+			convert_gentoo || fatal "Cannot convert for Gentoo"
 			echo "Generate ebuild"
 			gen_ebuild
 			;;
